version: '3'
services:
  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 80
    ports:
      - "80:80"
    links:
      - redisdb
    environment:
      - REDIS_HOST=redisdb
      - REDIS_PORT=6378
    volumes:
      - ~/.cache/torch:/root/.cache/torch

  redisdb:
    image: "redis"
    command: --port 6378
    ports:
      - "6378:6378"

  worker:
    build: .
    command: python -m worker
    links:
      - redisdb
    environment:
      - REDIS_HOST=redisdb
      - REDIS_PORT=6378
    volumes:
      - ~/.cache/torch:/root/.cache/torch

